//Teste de Requisições REST - Livros
@baseURL = http://localhost:4000
@id = 61943ca0fc4ed206d5406fac
@ano = 2011
@autor = cline
@genero = Aventura
@titulo = two
@preco = 33.99

###
// GET - Lista todos os livros
GET {{baseURL}}/livros/
Content-Type: application/json

###
// GET - Lista um livro pelo id
GET {{baseURL}}/livros/{{id}}
Content-Type: application/json

###
// GET - Lista livros pelo ano de publicação
GET {{baseURL}}/livros/ano/{{ano}}
Content-Type: application/json

###
// GET - Lista livros pelo autor
GET {{baseURL}}/livros/autor/{{autor}}
Content-Type: application/json

###
// GET - Lista livros pelo genero
GET {{baseURL}}/livros/genero/{{genero}}
Content-Type: application/json

###
// GET - Lista livros pelo titulo
GET {{baseURL}}/livros/titulo/{{titulo}}
Content-Type: application/json

###
// GET - Lista livros pelo preco maximo
GET {{baseURL}}/livros/maxpreco/{{preco}}
Content-Type: application/json

###
// POST - Inclui um novo livro
POST {{baseURL}}/livros/
Content-Type: application/json

{
    "titulo": "Harry Potter e a Câmara Secreta",
    "descricao": "Depois de férias aborrecidas na casa dos tios trouxas, está na hora de Harry Potter voltar a estudar. Coisas acontecem, no entanto, para dificultar o regresso de Harry. Persistente e astuto, o herói não se deixa intimidar pelos obstáculos e, com a ajuda dos fiéis amigos Weasley, começa o ano letivo na Escola de Magia e Bruxaria de Hogwarts.",
    "anoPublicacao": 2002,
    "autor": "J.K. Rowling",
    "preco": 24.20,
    "genero": "Aventura"
}

###
// PUT - Altera um livro ja incluido no banco de dados
PUT {{baseURL}}/livros/
Content-Type: application/json

{
    "_id": "618f039a773ec50c659fc433",
    "titulo": "Ready Player One(livro)",
    "descricao": " A história se passa no ano de 2045, o mundo passa por uma grande crise energética, destruição e pobreza são os cenários mais comuns. A única escapatória é o OASIS, uma realidade virtual onde a maioria das pessoas passa grande parte do seu tempo. No OASIS as pessoas estudam, trabalham, jogam e interagem umas com as outras, assim elas economizam combustível (recurso escasso), evitam ficar muito tempo em contato com a poluição e tem mais acesso a cultura e informações.",
    "anoPublicacao": 2011,
    "autor": "Ernest Cline",
    "preco": 29.99,
    "genero": "Aventura"
}

### 
// DELETE - Deleta um livro pelo id informado
DELETE {{baseURL}}/livros/{{id}}
Content-Type: application/json
